name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest

      - name: Run linter
        run: uv run ruff check cipette/ tests/

      - name: Format code
        run: uv run ruff format cipette/ tests/

      - name: Build package
        run: uv build

      - name: Semantic Release
        run: uv run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload artifacts
        if: steps.semantic-release.outputs.new-release-published == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
