name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests python-dotenv PyGithub

    - name: Run database initialization
      run: |
        python src/database.py

    - name: Run basic syntax check
      run: |
        python -m py_compile src/config.py
        python -m py_compile src/database.py
        python -m py_compile src/data_collector.py